repository:
  name: formcreator
  description: GLPI Plugin Formcreator
  homepage: https://pluginsglpi.github.io/formcreator/
  topics: service-catalog, ticket, helpdesk, incident-management, servicedesk, itil, php, open-source, gplv3
  private: false
  has_issues: true
  has_wiki: false
  has_downloads: true
  default_branch: develop
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
labels:
  - name: api
    color: 0052cc
  - name: bug
    color: f44336
  - name: build
    color: 795548
  - name: cherry-pick
    color: af1c46
  - name: ci
    color: fbca04
  - name: cleanup
    color: c2e0c6
  - name: cli
    color: 444444
  - name: documentation
    color: 607d8b
  - name: duplicate
    color: 9e9e9e
  - name: feature
    color: 3f51b5
  - name: hacktoberfest
    color: ff625f
  - name: install
    color: ffa31a
  - name: invalid
    color: cddc39
  - name: locales
    color: d4c5f9
  - name: notification
    color: cc6699
  - name: performance
    color: 009688
  - name: question
    color: ff5722
  - name: refactor
    color: 9c27b0
  - name: style
    color: 2196f3
  - name: test
    color: 8bc34a
  - name: ui
    color: bfdadc
  - name: wontfix
    color: ffffff
  - name: help wanted
    color: 33aa3f
  - name: good first issue
    color: 7057ff
